### PR TITLE
Switch to gradle

### PR DESCRIPTION
**Pull request by Raynes**

### CODE REVIEW

**Comment by Raynes** [comment]
I for one welcome our new gradle overlords.

**Comment by Raynes** [comment]
Just added a bunch of stuff since nobody will merge it anyways :faketears:

**Comment by avram** [comment]
Next step is to make this build on travis-ci…

**Comment by Raynes** [comment]
<3

**Comment by avram** [comment]
Like this: https://travis-ci.org/scopely/leanplum-java-sdk

**Comment by Raynes** [comment]
Next step is to add tests, most likely. Which is what I'm currently working on.

**Comment by avram** [comment]
Oh that too. Can't believe I merged a PR without tests… that's why we need those green checkmarks

**Comment by Raynes** [comment]
Well I'm not writing tests for build.gradle.

**Pull request merged**
